// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbbYwVI0l8iYaFINus0t70riTWp5UVyRs',
    appId: '1:827450756686:web:51835b184620dedb873d1f',
    messagingSenderId: '827450756686',
    projectId: 'thrift754',
    authDomain: 'thrift754.firebaseapp.com',
    storageBucket: 'thrift754.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQW9YrPDYacnE51X7C3OufwbxBYpwjgak',
    appId: '1:827450756686:android:81d0470ddcf30313873d1f',
    messagingSenderId: '827450756686',
    projectId: 'thrift754',
    storageBucket: 'thrift754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgm9kMuTwCx8F7hJJOWWG8AQQ3n-GfRTc',
    appId: '1:827450756686:ios:7516f75f79faee91873d1f',
    messagingSenderId: '827450756686',
    projectId: 'thrift754',
    storageBucket: 'thrift754.appspot.com',
    iosClientId: '827450756686-g4fappd6le0shm13tmde3cqs4osfvr89.apps.googleusercontent.com',
    iosBundleId: 'com.example.beThrift',
  );
}
